#!/bin/sh
set -eu

GENERATED_DIR="${ASTERISK_GENERATED_DIR:-/etc/asterisk/generated}"
PJSIP_DIR="$GENERATED_DIR/pjsip"
PJSIP_DEVICES_DIR="$PJSIP_DIR/devices"
EXTENSIONS_DIR="$GENERATED_DIR/extensions"
EXTENSIONS_GROUPS_DIR="$EXTENSIONS_DIR/groups"

mkdir -p "$PJSIP_DEVICES_DIR" "$EXTENSIONS_GROUPS_DIR"

if [ ! -f "$PJSIP_DIR/transport.generated.conf" ]; then
  cat > "$PJSIP_DIR/transport.generated.conf" <<'EOF'
; Auto-generated by stack-pbx. Manual edits will be overwritten.
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0
EOF
fi

if [ ! -f "$PJSIP_DIR/stack-pbx.generated.conf" ]; then
  cat > "$PJSIP_DIR/stack-pbx.generated.conf" <<'EOF'
; Auto-generated by stack-pbx. Manual edits will be overwritten.
EOF
fi

if [ ! -f "$EXTENSIONS_DIR/stack-pbx.generated.conf" ]; then
  cat > "$EXTENSIONS_DIR/stack-pbx.generated.conf" <<'EOF'
; Auto-generated by stack-pbx. Manual edits will be overwritten.
EOF
fi
