/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateLayoutRouteImport } from './routes/(private)/layout'
import { Route as privatePageRouteImport } from './routes/(private)/page'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as privateGroupsPageRouteImport } from './routes/(private)/groups/page'
import { Route as privateDevicesPageRouteImport } from './routes/(private)/devices/page'
import { Route as privateAccountPageRouteImport } from './routes/(private)/account/page'
import { Route as privateGroupsGroupIdRouteImport } from './routes/(private)/groups/$groupId'
import { Route as privateDevicesDeviceIdRouteImport } from './routes/(private)/devices/$deviceId'

const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePageRoute = privatePageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const privateGroupsPageRoute = privateGroupsPageRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateDevicesPageRoute = privateDevicesPageRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateAccountPageRoute = privateAccountPageRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateGroupsGroupIdRoute = privateGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateDevicesDeviceIdRoute = privateDevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => privateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof privatePageRoute
  '/devices/$deviceId': typeof privateDevicesDeviceIdRoute
  '/groups/$groupId': typeof privateGroupsGroupIdRoute
  '/account/': typeof privateAccountPageRoute
  '/devices/': typeof privateDevicesPageRoute
  '/groups/': typeof privateGroupsPageRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof privatePageRoute
  '/devices/$deviceId': typeof privateDevicesDeviceIdRoute
  '/groups/$groupId': typeof privateGroupsGroupIdRoute
  '/account': typeof privateAccountPageRoute
  '/devices': typeof privateDevicesPageRoute
  '/groups': typeof privateGroupsPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateLayoutRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(private)/': typeof privatePageRoute
  '/(private)/devices/$deviceId': typeof privateDevicesDeviceIdRoute
  '/(private)/groups/$groupId': typeof privateGroupsGroupIdRoute
  '/(private)/account/': typeof privateAccountPageRoute
  '/(private)/devices/': typeof privateDevicesPageRoute
  '/(private)/groups/': typeof privateGroupsPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/'
    | '/devices/$deviceId'
    | '/groups/$groupId'
    | '/account/'
    | '/devices/'
    | '/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/'
    | '/devices/$deviceId'
    | '/groups/$groupId'
    | '/account'
    | '/devices'
    | '/groups'
  id:
    | '__root__'
    | '/(private)'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(private)/'
    | '/(private)/devices/$deviceId'
    | '/(private)/groups/$groupId'
    | '/(private)/account/'
    | '/(private)/devices/'
    | '/(private)/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privatePageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/groups/': {
      id: '/(private)/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof privateGroupsPageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/devices/': {
      id: '/(private)/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof privateDevicesPageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/account/': {
      id: '/(private)/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof privateAccountPageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/groups/$groupId': {
      id: '/(private)/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof privateGroupsGroupIdRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/devices/$deviceId': {
      id: '/(private)/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof privateDevicesDeviceIdRouteImport
      parentRoute: typeof privateLayoutRoute
    }
  }
}

interface privateLayoutRouteChildren {
  privatePageRoute: typeof privatePageRoute
  privateDevicesDeviceIdRoute: typeof privateDevicesDeviceIdRoute
  privateGroupsGroupIdRoute: typeof privateGroupsGroupIdRoute
  privateAccountPageRoute: typeof privateAccountPageRoute
  privateDevicesPageRoute: typeof privateDevicesPageRoute
  privateGroupsPageRoute: typeof privateGroupsPageRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privatePageRoute: privatePageRoute,
  privateDevicesDeviceIdRoute: privateDevicesDeviceIdRoute,
  privateGroupsGroupIdRoute: privateGroupsGroupIdRoute,
  privateAccountPageRoute: privateAccountPageRoute,
  privateDevicesPageRoute: privateDevicesPageRoute,
  privateGroupsPageRoute: privateGroupsPageRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateLayoutRoute: privateLayoutRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
