[global]
type=global
user_agent=stack-pbx
endpoint_identifier_order=auth_username,username,ip,anonymous

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0

#include "generated/pjsip/stack-pbx.generated.conf"
