[CmdletBinding()]
param(
  [string]$InstallRoot = $(Split-Path -Path (Split-Path -Path (Split-Path -Path $PSScriptRoot -Parent) -Parent) -Parent),
  [string]$ProgramDataRoot = "C:\ProgramData\Khomp Stack",
  [string]$WinSWExecutablePath = "",
  [string]$AppVersion = "0.0.0"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-FullPath {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  return [System.IO.Path]::GetFullPath($Path)
}

function Assert-PathExists {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path,
    [Parameter(Mandatory = $true)]
    [string]$Description
  )

  if (-not (Test-Path -LiteralPath $Path)) {
    throw "$Description was not found at '$Path'."
  }
}

function ConvertTo-XmlAttributeValue {
  param(
    [Parameter(Mandatory = $true)]
    [AllowEmptyString()]
    [string]$Value
  )

  return [System.Security.SecurityElement]::Escape($Value)
}

function Read-EnvFile {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  $values = @{}

  foreach ($line in Get-Content -LiteralPath $Path) {
    if ([string]::IsNullOrWhiteSpace($line)) {
      continue
    }

    $trimmedLine = $line.Trim()

    if ($trimmedLine.StartsWith("#")) {
      continue
    }

    $separatorIndex = $trimmedLine.IndexOf("=")

    if ($separatorIndex -lt 1) {
      continue
    }

    $key = $trimmedLine.Substring(0, $separatorIndex).Trim().TrimStart([char]0xFEFF)
    $value = $trimmedLine.Substring($separatorIndex + 1)
    $values[$key] = $value
  }

  return $values
}

function ConvertTo-WinSWEnvEntries {
  param(
    [Parameter(Mandatory = $true)]
    [hashtable]$Values
  )

  $lines = foreach ($key in ($Values.Keys | Sort-Object)) {
    "  <env name=""$(ConvertTo-XmlAttributeValue -Value $key)"" value=""$(ConvertTo-XmlAttributeValue -Value ([string]$Values[$key]))"" />"
  }

  return ($lines -join [Environment]::NewLine)
}

function Render-WinSWTemplate {
  param(
    [Parameter(Mandatory = $true)]
    [string]$TemplatePath,
    [Parameter(Mandatory = $true)]
    [string]$DestinationPath,
    [Parameter(Mandatory = $true)]
    [hashtable]$Tokens
  )

  $content = Get-Content -LiteralPath $TemplatePath -Raw

  foreach ($key in $Tokens.Keys) {
    $content = $content.Replace($key, $Tokens[$key])
  }

  Set-Content -LiteralPath $DestinationPath -Value $content -Encoding UTF8
}

function Write-MqttBrokerConfig {
  param(
    [Parameter(Mandatory = $true)]
    [string]$InstallRootPath,
    [Parameter(Mandatory = $true)]
    [string]$ProgramDataRootPath,
    [Parameter(Mandatory = $true)]
    [hashtable]$RuntimeValues
  )

  $mosquittoRoot = Join-Path $InstallRootPath "mqtt\mosquitto"
  $mosquittoExecutable = Join-Path $mosquittoRoot "mosquitto.exe"
  $mosquittoPasswordExecutable = Join-Path $mosquittoRoot "mosquitto_passwd.exe"

  Assert-PathExists -Path $mosquittoExecutable -Description "Mosquitto executable"
  Assert-PathExists -Path $mosquittoPasswordExecutable -Description "Mosquitto password tool"

  $mqttConfigRoot = Join-Path $ProgramDataRootPath "config\mqtt"
  $mqttDataRoot = Join-Path $ProgramDataRootPath "data\mqtt"
  $mqttLogRoot = Join-Path $ProgramDataRootPath "logs\mqtt"
  $mqttConfigPath = Join-Path $mqttConfigRoot "mosquitto.conf"
  $mqttPasswordPath = Join-Path $mqttConfigRoot "passwords.txt"

  New-Item -Path $mqttConfigRoot -ItemType Directory -Force | Out-Null
  New-Item -Path $mqttDataRoot -ItemType Directory -Force | Out-Null
  New-Item -Path $mqttLogRoot -ItemType Directory -Force | Out-Null

  $mqttPort = [string]$RuntimeValues["MQTT_BROKER_PORT"]
  $mqttUsername = [string]$RuntimeValues["MQTT_BROKER_USERNAME"]
  $mqttPassword = [string]$RuntimeValues["MQTT_BROKER_PASSWORD"]

  if ([string]::IsNullOrWhiteSpace($mqttUsername)) {
    throw "MQTT_BROKER_USERNAME is required to configure the local MQTT broker."
  }

  if ([string]::IsNullOrWhiteSpace($mqttPassword)) {
    throw "MQTT_BROKER_PASSWORD is required to configure the local MQTT broker."
  }

  $config = @(
    "# Auto-generated by Khomp Stack. Manual edits may be overwritten."
    "listener $mqttPort 0.0.0.0"
    "allow_anonymous false"
    "password_file $($mqttPasswordPath -replace '\\', '/')"
    "persistence true"
    "persistence_location $((Join-Path $mqttDataRoot '') -replace '\\', '/')"
    "log_dest stdout"
    "connection_messages true"
  ) -join [Environment]::NewLine

  $utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($mqttConfigPath, $config, $utf8WithoutBom)

  & $mosquittoPasswordExecutable -b -c $mqttPasswordPath $mqttUsername $mqttPassword | Out-Null
  & icacls.exe $mqttConfigRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null
  & icacls.exe $mqttDataRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null
  & icacls.exe $mqttLogRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null
  & icacls.exe $mqttConfigPath /grant "*S-1-5-18:F" /grant "*S-1-5-32-544:F" | Out-Null
  & icacls.exe $mqttPasswordPath /grant "*S-1-5-18:F" /grant "*S-1-5-32-544:F" | Out-Null

  New-NetFirewallRule `
    -DisplayName "Khomp Stack MQTT Broker" `
    -Direction Inbound `
    -Action Allow `
    -Protocol TCP `
    -LocalPort ([int]$mqttPort) `
    -Program $mosquittoExecutable `
    -Profile Any `
    -ErrorAction SilentlyContinue | Out-Null

  [pscustomobject]@{
    ConfigPath = $mqttConfigPath
    PasswordPath = $mqttPasswordPath
    Port = [int]$mqttPort
    Username = $mqttUsername
  }
}

function ConvertTo-AsteriskPath {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  return ($Path -replace "\\", "/")
}

function Write-Utf8File {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path,
    [Parameter(Mandatory = $true)]
    [string]$Content
  )

  $utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $utf8WithoutBom)
}

function Write-AsteriskConfig {
  param(
    [Parameter(Mandatory = $true)]
    [string]$InstallRootPath,
    [Parameter(Mandatory = $true)]
    [string]$ProgramDataRootPath,
    [Parameter(Mandatory = $true)]
    [hashtable]$RuntimeValues
  )

  $asteriskRoot = Join-Path $InstallRootPath "asterisk"
  $asteriskExecutable = Join-Path $asteriskRoot "asterisk.exe"
  Assert-PathExists -Path $asteriskExecutable -Description "Asterisk executable"

  $configRoot = Join-Path $ProgramDataRootPath "config\asterisk"
  $generatedRoot = Join-Path $configRoot "generated"
  $pjsipRoot = Join-Path $generatedRoot "pjsip"
  $pjsipDevicesRoot = Join-Path $pjsipRoot "devices"
  $extensionsRoot = Join-Path $generatedRoot "extensions"
  $extensionsGroupsRoot = Join-Path $extensionsRoot "groups"
  $dataRoot = Join-Path $ProgramDataRootPath "data\asterisk"
  $spoolRoot = Join-Path $ProgramDataRootPath "spool\asterisk"
  $runRoot = Join-Path $ProgramDataRootPath "run\asterisk"
  $logRoot = Join-Path $ProgramDataRootPath "logs\asterisk"
  $moduleRoot = Join-Path $asteriskRoot "modules"

  @(
    $configRoot,
    $pjsipDevicesRoot,
    $extensionsGroupsRoot,
    (Join-Path $dataRoot "agi-bin"),
    $spoolRoot,
    $runRoot,
    $logRoot
  ) | ForEach-Object {
    New-Item -Path $_ -ItemType Directory -Force | Out-Null
  }

  $amiUsername = [string]$RuntimeValues["ASTERISK_AMI_USERNAME"]
  $amiPassword = [string]$RuntimeValues["ASTERISK_AMI_PASSWORD"]
  $amiPort = [string]$RuntimeValues["ASTERISK_AMI_PORT"]
  $sipPort = [string]$RuntimeValues["ASTERISK_DEVICE_SIP_PORT"]
  $pbxHost = [string]$RuntimeValues["ASTERISK_DEVICE_HOST"]

  if ([string]::IsNullOrWhiteSpace($amiUsername) -or [string]::IsNullOrWhiteSpace($amiPassword)) {
    throw "ASTERISK_AMI_USERNAME and ASTERISK_AMI_PASSWORD are required to configure Asterisk."
  }

  Write-Utf8File -Path (Join-Path $configRoot "asterisk.conf") -Content (@(
    "[directories]"
    "astetcdir => $(ConvertTo-AsteriskPath -Path $configRoot)"
    "astmoddir => $(ConvertTo-AsteriskPath -Path $moduleRoot)"
    "astvarlibdir => $(ConvertTo-AsteriskPath -Path $dataRoot)"
    "astdbdir => $(ConvertTo-AsteriskPath -Path $dataRoot)"
    "astkeydir => $(ConvertTo-AsteriskPath -Path $dataRoot)"
    "astdatadir => $(ConvertTo-AsteriskPath -Path $dataRoot)"
    "astagidir => $(ConvertTo-AsteriskPath -Path (Join-Path $dataRoot "agi-bin"))"
    "astspooldir => $(ConvertTo-AsteriskPath -Path $spoolRoot)"
    "astrundir => $(ConvertTo-AsteriskPath -Path $runRoot)"
    "astlogdir => $(ConvertTo-AsteriskPath -Path $logRoot)"
    "astsbindir => $(ConvertTo-AsteriskPath -Path $asteriskRoot)"
    ""
    "[options]"
    "transmit_silence_during_record = yes"
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $configRoot "http.conf") -Content (@(
    "[general]"
    "enabled=yes"
    "bindaddr=0.0.0.0"
    "bindport=8088"
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $configRoot "manager.conf") -Content (@(
    "[general]"
    "enabled = yes"
    "webenabled = no"
    "port = $amiPort"
    "bindaddr = 127.0.0.1"
    "displayconnects = no"
    ""
    "[$amiUsername]"
    "secret = $amiPassword"
    "read = all"
    "write = all"
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $configRoot "pjsip.conf") -Content (@(
    "[global]"
    "type=global"
    "user_agent=stack-pbx"
    "endpoint_identifier_order=auth_username,username,ip,anonymous"
    ""
    "#include `"generated/pjsip/transport.generated.conf`""
    "#include `"generated/pjsip/stack-pbx.generated.conf`""
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $configRoot "extensions.conf") -Content (@(
    "[general]"
    "static=yes"
    "writeprotect=no"
    "clearglobalvars=no"
    ""
    "[globals]"
    ""
    "#include `"generated/extensions/stack-pbx.generated.conf`""
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $configRoot "rtp.conf") -Content (@(
    "[general]"
    "rtpstart=10000"
    "rtpend=10100"
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $configRoot "logger.conf") -Content (@(
    "[general]"
    "dateformat=%F %T"
    ""
    "[logfiles]"
    "console => notice,warning,error,verbose"
    "messages => notice,warning,error"
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $configRoot "modules.conf") -Content (@(
    "[modules]"
    "autoload=yes"
    "noload => chan_alsa.so"
    "noload => chan_console.so"
    "noload => res_config_ldap.so"
    "noload => res_config_pgsql.so"
  ) -join [Environment]::NewLine)

  if (-not (Test-Path -LiteralPath (Join-Path $pjsipRoot "transport.generated.conf"))) {
    Write-Utf8File -Path (Join-Path $pjsipRoot "transport.generated.conf") -Content (@(
      "; Auto-generated by stack-pbx. Manual edits will be overwritten."
      "[transport-udp]"
      "type=transport"
      "protocol=udp"
      "bind=0.0.0.0:$sipPort"
      "external_media_address=$pbxHost"
      "external_signaling_address=$pbxHost"
      "local_net=10.0.0.0/8"
      "local_net=172.16.0.0/12"
      "local_net=192.168.0.0/16"
      ""
      "[transport-ws]"
      "type=transport"
      "protocol=ws"
      "bind=0.0.0.0"
    ) -join [Environment]::NewLine)
  }

  foreach ($path in @(
    (Join-Path $pjsipRoot "stack-pbx.generated.conf"),
    (Join-Path $extensionsRoot "stack-pbx.generated.conf")
  )) {
    if (-not (Test-Path -LiteralPath $path)) {
      Write-Utf8File -Path $path -Content "; Auto-generated by stack-pbx. Manual edits will be overwritten."
    }
  }

  & icacls.exe $configRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null
  & icacls.exe $dataRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null
  & icacls.exe $spoolRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null
  & icacls.exe $logRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null

  foreach ($rule in @(
    @{ Name = "Khomp Stack Asterisk SIP UDP"; Protocol = "UDP"; Port = $sipPort },
    @{ Name = "Khomp Stack Asterisk SIP TCP"; Protocol = "TCP"; Port = $sipPort },
    @{ Name = "Khomp Stack Asterisk HTTP WebSocket"; Protocol = "TCP"; Port = "8088" },
    @{ Name = "Khomp Stack Asterisk RTP"; Protocol = "UDP"; Port = "10000-10100" }
  )) {
    New-NetFirewallRule `
      -DisplayName $rule.Name `
      -Direction Inbound `
      -Action Allow `
      -Protocol $rule.Protocol `
      -LocalPort $rule.Port `
      -Program $asteriskExecutable `
      -Profile Any `
      -ErrorAction SilentlyContinue | Out-Null
  }

  [pscustomobject]@{
    ConfigRoot = $configRoot
    GeneratedRoot = $generatedRoot
    Executable = $asteriskExecutable
    SipPort = [int]$sipPort
    HttpPort = 8088
    RtpPorts = "10000-10100"
  }
}

function Write-FreeSwitchConfig {
  param(
    [Parameter(Mandatory = $true)]
    [string]$InstallRootPath,
    [Parameter(Mandatory = $true)]
    [string]$ProgramDataRootPath,
    [Parameter(Mandatory = $true)]
    [hashtable]$RuntimeValues
  )

  $freeSwitchRoot = Join-Path $InstallRootPath "freeswitch"
  $freeSwitchExecutable = Join-Path $freeSwitchRoot "FreeSwitchConsole.exe"
  Assert-PathExists -Path $freeSwitchExecutable -Description "FreeSWITCH executable"

  $programDataParent = Split-Path -Parent $ProgramDataRootPath
  $freeSwitchStateRoot = Join-Path $programDataParent "KhompStack\freeswitch"
  $configRoot = Join-Path $ProgramDataRootPath "config\freeswitch"
  $logRoot = Join-Path $freeSwitchStateRoot "logs"
  $serviceLogRoot = Join-Path $freeSwitchStateRoot "service-logs"
  $dbRoot = Join-Path $freeSwitchStateRoot "db"
  $runRoot = Join-Path $freeSwitchStateRoot "run"
  $tempRoot = Join-Path $freeSwitchStateRoot "temp"
  $scriptsRoot = Join-Path $configRoot "scripts"
  $dialplanRoot = Join-Path $configRoot "dialplan\default"
  $directoryRoot = Join-Path $configRoot "directory\default"
  $autoloadRoot = Join-Path $configRoot "autoload_configs"
  $sipProfilesRoot = Join-Path $configRoot "sip_profiles"
  $sourceConfigRoot = Join-Path $freeSwitchRoot "conf"

  @(
    $configRoot,
    $logRoot,
    $serviceLogRoot,
    $dbRoot,
    $runRoot,
    $tempRoot,
    $scriptsRoot,
    $dialplanRoot,
    $directoryRoot,
    $autoloadRoot,
    $sipProfilesRoot
  ) | ForEach-Object {
    New-Item -Path $_ -ItemType Directory -Force | Out-Null
  }

  if ((Test-Path -LiteralPath $sourceConfigRoot) -and (-not (Test-Path -LiteralPath (Join-Path $configRoot "freeswitch.xml")))) {
    Copy-Item -Path (Join-Path $sourceConfigRoot "*") -Destination $configRoot -Recurse -Force
  }

  $eventSocketPassword = [string]$RuntimeValues["FREESWITCH_ESL_PASSWORD"]
  $eventSocketPort = [string]$RuntimeValues["FREESWITCH_ESL_PORT"]
  $sipPort = [string]$RuntimeValues["FREESWITCH_SIP_PORT"]
  $wsPort = [string]$RuntimeValues["FREESWITCH_WS_PORT"]
  $rtpStartPort = [string]$RuntimeValues["FREESWITCH_RTP_START_PORT"]
  $rtpEndPort = [string]$RuntimeValues["FREESWITCH_RTP_END_PORT"]
  $domain = [string]$RuntimeValues["FREESWITCH_DOMAIN"]

  if ([string]::IsNullOrWhiteSpace($eventSocketPassword)) {
    throw "FREESWITCH_ESL_PASSWORD is required to configure FreeSWITCH."
  }

  if ([string]::IsNullOrWhiteSpace($domain)) {
    throw "FREESWITCH_DOMAIN is required to configure FreeSWITCH."
  }

  Write-Utf8File -Path (Join-Path $configRoot "vars.xml") -Content (@(
    "<include>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"domain=$domain`"/>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"domain_name=$domain`"/>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"local_ip_v4=$domain`"/>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"external_sip_ip=$domain`"/>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"external_rtp_ip=$domain`"/>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"internal_sip_port=$sipPort`"/>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"internal_ws_port=$wsPort`"/>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"external_sip_port=5080`"/>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"external_tls_port=5081`"/>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"rtp_start_port=$rtpStartPort`"/>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"rtp_end_port=$rtpEndPort`"/>"
    "  <X-PRE-PROCESS cmd=`"set`" data=`"default_password=$eventSocketPassword`"/>"
    "</include>"
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $autoloadRoot "event_socket.conf.xml") -Content (@(
    "<configuration name=`"event_socket.conf`" description=`"Socket Client`">"
    "  <settings>"
    "    <param name=`"nat-map`" value=`"false`"/>"
    "    <param name=`"listen-ip`" value=`"127.0.0.1`"/>"
    "    <param name=`"listen-port`" value=`"$eventSocketPort`"/>"
    "    <param name=`"password`" value=`"$eventSocketPassword`"/>"
    "  </settings>"
    "</configuration>"
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $autoloadRoot "switch.conf.xml") -Content (@(
    "<configuration name=`"switch.conf`" description=`"Core Configuration`">"
    "  <settings>"
    "    <param name=`"rtp-start-port`" value=`"$rtpStartPort`"/>"
    "    <param name=`"rtp-end-port`" value=`"$rtpEndPort`"/>"
    "    <param name=`"max-sessions`" value=`"100`"/>"
    "    <param name=`"sessions-per-second`" value=`"30`"/>"
    "  </settings>"
    "</configuration>"
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $autoloadRoot "modules.conf.xml") -Content (@(
    "<configuration name=`"modules.conf`" description=`"Modules`">"
    "  <modules>"
    "    <load module=`"mod_console`"/>"
    "    <load module=`"mod_logfile`"/>"
    "    <load module=`"mod_commands`"/>"
    "    <load module=`"mod_dptools`"/>"
    "    <load module=`"mod_dialplan_xml`"/>"
    "    <load module=`"mod_event_socket`"/>"
    "    <load module=`"mod_conference`"/>"
    "    <load module=`"mod_hash`"/>"
    "    <load module=`"mod_sofia`"/>"
    "    <load module=`"mod_opus`"/>"
    "  </modules>"
    "</configuration>"
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $autoloadRoot "sofia.conf.xml") -Content (@(
    "<configuration name=`"sofia.conf`" description=`"Sofia Endpoint`">"
    "  <global_settings>"
    "    <param name=`"log-level`" value=`"0`"/>"
    "  </global_settings>"
    "  <profiles>"
    "    <X-PRE-PROCESS cmd=`"include`" data=`"../sip_profiles/*.xml`"/>"
    "  </profiles>"
    "</configuration>"
  ) -join [Environment]::NewLine)

  Write-Utf8File -Path (Join-Path $sipProfilesRoot "internal.xml") -Content (@(
    "<profile name=`"internal`">"
    "  <aliases>"
    "    <alias name=`"default`"/>"
    "  </aliases>"
    "  <domains>"
    "    <domain name=`"all`" alias=`"true`" parse=`"true`"/>"
    "  </domains>"
    "  <settings>"
    "    <param name=`"debug`" value=`"0`"/>"
    "    <param name=`"sip-trace`" value=`"no`"/>"
    "    <param name=`"sip-capture`" value=`"no`"/>"
    "    <param name=`"rfc2833-pt`" value=`"101`"/>"
    "    <param name=`"sip-port`" value=`"$sipPort`"/>"
    "    <param name=`"dialplan`" value=`"XML`"/>"
    "    <param name=`"context`" value=`"default`"/>"
    "    <param name=`"dtmf-duration`" value=`"2000`"/>"
    "    <param name=`"inbound-codec-prefs`" value=`"PCMU,PCMA,OPUS`"/>"
    "    <param name=`"outbound-codec-prefs`" value=`"PCMU,PCMA,OPUS`"/>"
    "    <param name=`"rtp-ip`" value=`"$domain`"/>"
    "    <param name=`"sip-ip`" value=`"$domain`"/>"
    "    <param name=`"ext-rtp-ip`" value=`"$domain`"/>"
    "    <param name=`"ext-sip-ip`" value=`"$domain`"/>"
    "    <param name=`"ws-binding`" value=`":$wsPort`"/>"
    "    <param name=`"auth-calls`" value=`"true`"/>"
    "    <param name=`"accept-blind-reg`" value=`"false`"/>"
    "    <param name=`"force-register-domain`" value=`"$domain`"/>"
    "    <param name=`"force-subscription-domain`" value=`"$domain`"/>"
    "    <param name=`"force-register-db-domain`" value=`"$domain`"/>"
    "    <param name=`"NDLB-force-rport`" value=`"safe`"/>"
    "    <param name=`"inbound-late-negotiation`" value=`"true`"/>"
    "    <param name=`"inbound-zrtp-passthru`" value=`"true`"/>"
    "  </settings>"
    "</profile>"
  ) -join [Environment]::NewLine)

  foreach ($path in @(
    (Join-Path $dialplanRoot "00-stack-pbx.xml"),
    (Join-Path $directoryRoot "00-stack-pbx.xml")
  )) {
    if (-not (Test-Path -LiteralPath $path)) {
      Write-Utf8File -Path $path -Content "<include />"
    }
  }

  & icacls.exe $configRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null
  & icacls.exe $dbRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null
  & icacls.exe $runRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null
  & icacls.exe $logRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null
  & icacls.exe $serviceLogRoot /inheritance:e /grant "*S-1-5-18:(OI)(CI)F" /grant "*S-1-5-32-544:(OI)(CI)F" | Out-Null

  foreach ($rule in @(
    @{ Name = "Khomp Stack FreeSWITCH SIP UDP"; Protocol = "UDP"; Port = $sipPort },
    @{ Name = "Khomp Stack FreeSWITCH SIP TCP"; Protocol = "TCP"; Port = $sipPort },
    @{ Name = "Khomp Stack FreeSWITCH SIP WebSocket"; Protocol = "TCP"; Port = $wsPort },
    @{ Name = "Khomp Stack FreeSWITCH RTP"; Protocol = "UDP"; Port = "$rtpStartPort-$rtpEndPort" }
  )) {
    New-NetFirewallRule `
      -DisplayName $rule.Name `
      -Direction Inbound `
      -Action Allow `
      -Protocol $rule.Protocol `
      -LocalPort $rule.Port `
      -Program $freeSwitchExecutable `
      -Profile Any `
      -ErrorAction SilentlyContinue | Out-Null
  }

  [pscustomobject]@{
    ConfigRoot = $configRoot
    Executable = $freeSwitchExecutable
    StateRoot = $freeSwitchStateRoot
    SipPort = [int]$sipPort
    WebSocketPort = [int]$wsPort
    RtpPorts = "$rtpStartPort-$rtpEndPort"
    EventSocketPort = [int]$eventSocketPort
  }
}

function Wait-ServiceState {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Name,
    [Parameter(Mandatory = $true)]
    [ValidateSet("Running", "Stopped")]
    [string]$DesiredStatus,
    [int]$TimeoutSeconds = 30,
    [int]$PollIntervalMilliseconds = 500,
    [switch]$AllowMissing
  )

  $deadline = (Get-Date).AddSeconds($TimeoutSeconds)

  while ((Get-Date) -lt $deadline) {
    $service = Get-Service -Name $Name -ErrorAction SilentlyContinue

    if (-not $service) {
      if ($AllowMissing -or ($DesiredStatus -eq "Stopped")) {
        return $true
      }

      Start-Sleep -Milliseconds $PollIntervalMilliseconds
      continue
    }

    if ($service.Status.ToString() -eq $DesiredStatus) {
      return $true
    }

    Start-Sleep -Milliseconds $PollIntervalMilliseconds
  }

  throw "Service '$Name' did not reach state '$DesiredStatus' within $TimeoutSeconds seconds."
}

function Wait-HttpEndpoint {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Url,
    [int]$TimeoutSeconds = 60,
    [int]$PollIntervalMilliseconds = 1000
  )

  $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
  $lastError = $null

  while ((Get-Date) -lt $deadline) {
    try {
      $response = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 5

      if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 500) {
        return $true
      }

      $lastError = "HTTP $($response.StatusCode)"
    } catch {
      $lastError = $_.Exception.Message
    }

    Start-Sleep -Milliseconds $PollIntervalMilliseconds
  }

  throw "HTTP endpoint '$Url' did not become available within $TimeoutSeconds seconds. Last error: $lastError"
}

function Resolve-WinSWExecutablePath {
  param(
    [Parameter(Mandatory = $true)]
    [string]$InstallRootPath,
    [Parameter(Mandatory = $true)]
    [string]$ScriptRootPath,
    [string]$RequestedPath
  )

  $candidates = @()

  if (-not [string]::IsNullOrWhiteSpace($RequestedPath)) {
    $candidates += (Get-FullPath -Path $RequestedPath)
  }

  $candidates += @(
    (Get-FullPath -Path (Join-Path $InstallRootPath "vendor\winsw\WinSW-x64.exe")),
    (Get-FullPath -Path (Join-Path $InstallRootPath "vendor\winsw\winsw-x64.exe")),
    (Get-FullPath -Path (Join-Path $InstallRootPath "winsw\WinSW-x64.exe")),
    (Get-FullPath -Path (Join-Path $InstallRootPath "ops\windows\vendor\winsw\WinSW-x64.exe")),
    (Get-FullPath -Path (Join-Path $ScriptRootPath "..\vendor\winsw\WinSW-x64.exe"))
  ) | Select-Object -Unique

  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate) {
      return $candidate
    }
  }

  $candidateList = $candidates | ForEach-Object { " - $_" }
  $message = @(
    "Unable to locate WinSW-x64.exe."
    "Looked in:"
    $candidateList
    "Pass -WinSWExecutablePath explicitly or ensure the installer places WinSW in one of the expected package locations."
  ) -join [Environment]::NewLine

  throw $message
}

function Install-KhompService {
  param(
    [Parameter(Mandatory = $true)]
    [hashtable]$Service,
    [Parameter(Mandatory = $true)]
    [string]$InstallRootPath,
    [Parameter(Mandatory = $true)]
    [string]$ProgramDataRootPath,
    [Parameter(Mandatory = $true)]
    [string]$WinSWPath,
    [Parameter(Mandatory = $true)]
    [hashtable]$RuntimeValues
  )

  Assert-PathExists -Path $Service.BinaryPath -Description "$($Service.Id) executable"
  Assert-PathExists -Path $Service.TemplatePath -Description "$($Service.Id) WinSW template"

  $serviceRoot = Join-Path $InstallRootPath "services\\$($Service.Id)"
  $serviceExecutablePath = Join-Path $serviceRoot "$($Service.Id).exe"
  $serviceConfigPath = Join-Path $serviceRoot "$($Service.Id).xml"
  $serviceLogPath = Join-Path $ProgramDataRootPath "logs\\$($Service.LogDirectory)"

  if (Get-Service -Name $Service.Id -ErrorAction SilentlyContinue) {
    try {
      Stop-Service -Name $Service.Id -ErrorAction Stop
      Wait-ServiceState -Name $Service.Id -DesiredStatus "Stopped"
    } catch {
      Write-Warning "Failed to stop existing service '$($Service.Id)': $($_.Exception.Message)"
    }

    if (Test-Path -LiteralPath $serviceExecutablePath) {
      & $serviceExecutablePath uninstall | Out-Null
    } else {
      & sc.exe delete $($Service.Id) | Out-Null
    }

    Wait-ServiceState -Name $Service.Id -DesiredStatus "Stopped" -AllowMissing
  }

  New-Item -Path $serviceRoot -ItemType Directory -Force | Out-Null
  New-Item -Path $serviceLogPath -ItemType Directory -Force | Out-Null

  Copy-Item -LiteralPath $WinSWPath -Destination $serviceExecutablePath -Force

  Render-WinSWTemplate -TemplatePath $Service.TemplatePath -DestinationPath $serviceConfigPath -Tokens @{
    "__INSTALL_ROOT__" = $InstallRootPath
    "__PROGRAM_DATA_ROOT__" = $ProgramDataRootPath
    "__FREESWITCH_STATE_ROOT__" = (Join-Path (Split-Path -Parent $ProgramDataRootPath) "KhompStack\freeswitch")
    "__ENV_ENTRIES__" = (ConvertTo-WinSWEnvEntries -Values $RuntimeValues)
  }

  & $serviceExecutablePath install | Out-Null
  Start-Service -Name $Service.Id
  Wait-ServiceState -Name $Service.Id -DesiredStatus "Running"

  [pscustomobject]@{
    ServiceId = $Service.Id
    WrapperExecutable = $serviceExecutablePath
    WrapperConfig = $serviceConfigPath
    ServiceRoot = $serviceRoot
  }
}

$installRootPath = Get-FullPath -Path $InstallRoot
$programDataRootPath = Get-FullPath -Path $ProgramDataRoot
$installLogRoot = Join-Path $programDataRootPath "logs"
New-Item -Path $installLogRoot -ItemType Directory -Force | Out-Null
try {
  Start-Transcript -Path (Join-Path $installLogRoot "install-services.log") -Append | Out-Null
} catch {
  Write-Warning "Failed to start install transcript: $($_.Exception.Message)"
}

$resolvedWinSWPath = Resolve-WinSWExecutablePath `
  -InstallRootPath $installRootPath `
  -ScriptRootPath $PSScriptRoot `
  -RequestedPath $WinSWExecutablePath

$bootstrapScriptPath = Join-Path $PSScriptRoot "bootstrap-config.ps1"
Assert-PathExists -Path $bootstrapScriptPath -Description "Bootstrap script"

$bootstrapResult = & $bootstrapScriptPath -ProgramDataRoot $programDataRootPath -InstallRoot $installRootPath -AppVersion $AppVersion
$runtimeEnvPath = Join-Path $programDataRootPath "config\service-runtime.env"
Assert-PathExists -Path $runtimeEnvPath -Description "Service runtime env file"
$runtimeValues = Read-EnvFile -Path $runtimeEnvPath
$mqttResult = Write-MqttBrokerConfig `
  -InstallRootPath $installRootPath `
  -ProgramDataRootPath $programDataRootPath `
  -RuntimeValues $runtimeValues

$freeSwitchResult = Write-FreeSwitchConfig `
  -InstallRootPath $installRootPath `
  -ProgramDataRootPath $programDataRootPath `
  -RuntimeValues $runtimeValues

$initPostgresScriptPath = Join-Path $PSScriptRoot "init-postgres.ps1"
Assert-PathExists -Path $initPostgresScriptPath -Description "PostgreSQL initialization script"
$postgresResult = & $initPostgresScriptPath -InstallRoot $installRootPath -ProgramDataRoot $programDataRootPath

$services = @(
  @{
    Id = "KhompStack-Mqtt"
    TemplatePath = Get-FullPath -Path (Join-Path $installRootPath "ops\\windows\\winsw\\mqtt.xml")
    BinaryPath = Get-FullPath -Path (Join-Path $installRootPath "mqtt\\mosquitto\\mosquitto.exe")
    LogDirectory = "mqtt"
  },
  @{
    Id = "KhompStack-FreeSWITCH"
    TemplatePath = Get-FullPath -Path (Join-Path $installRootPath "ops\\windows\\winsw\\freeswitch.xml")
      BinaryPath = Get-FullPath -Path (Join-Path $installRootPath "freeswitch\\FreeSwitchConsole.exe")
    LogDirectory = "freeswitch-service"
  },
  @{
    Id = "KhompStack-Backend"
    TemplatePath = Get-FullPath -Path (Join-Path $installRootPath "ops\\windows\\winsw\\backend.xml")
    BinaryPath = Get-FullPath -Path (Join-Path $installRootPath "backend\\server.exe")
    LogDirectory = "backend"
  },
  @{
    Id = "KhompStack-Ingest"
    TemplatePath = Get-FullPath -Path (Join-Path $installRootPath "ops\\windows\\winsw\\ingest.xml")
    BinaryPath = Get-FullPath -Path (Join-Path $installRootPath "ingest\\ingest.exe")
    LogDirectory = "ingest"
  },
  @{
    Id = "KhompStack-MulticastAgent"
    TemplatePath = Get-FullPath -Path (Join-Path $installRootPath "ops\\windows\\winsw\\multicast-agent.xml")
    BinaryPath = Get-FullPath -Path (Join-Path $installRootPath "multicast-agent\\multicast-agent.exe")
    LogDirectory = "multicast-agent"
  }
)

$installedServices = foreach ($service in $services) {
  Install-KhompService `
    -Service $service `
    -InstallRootPath $installRootPath `
    -ProgramDataRootPath $programDataRootPath `
    -WinSWPath $resolvedWinSWPath `
    -RuntimeValues $runtimeValues
}

$backendPort = [int]$runtimeValues["PORT"]
$null = Wait-HttpEndpoint -Url "http://127.0.0.1:$backendPort/" -TimeoutSeconds 90

[pscustomobject]@{
  RuntimeEnvPath = $runtimeEnvPath
  RuntimeValues = $runtimeValues
  WinSWPath = $resolvedWinSWPath
  BootstrapResult = $bootstrapResult
  MqttResult = $mqttResult
  FreeSwitchResult = $freeSwitchResult
  PostgresResult = $postgresResult
  InstalledServices = $installedServices
}

try {
  Stop-Transcript | Out-Null
} catch {
  Write-Warning "Failed to stop install transcript: $($_.Exception.Message)"
}
