import { db } from "@stack-pbx/db";
import {
  device as deviceTable,
  deviceGroup as deviceGroupTable,
  user as userTable,
} from "@stack-pbx/db/schema/index";
import { env } from "@stack-pbx/env/server";
import { eq } from "drizzle-orm";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import net from "node:net";
import path from "node:path";
import { AppError } from "../../../core/errors/app-error";
import { sanitizeSipToken } from "./sip-identity";

const workspaceRoot = process.cwd();
const defaultPjsipDevicesDir = path.join(workspaceRoot, "infra/asterisk/generated/pjsip/devices");
const defaultExtensionsGroupsDir = path.join(
  workspaceRoot,
  "infra/asterisk/generated/extensions/groups",
);
const defaultPjsipIndexFile = path.join(
  workspaceRoot,
  "infra/asterisk/generated/pjsip/stack-pbx.generated.conf",
);
const defaultPjsipTransportFile = path.join(
  workspaceRoot,
  "infra/asterisk/generated/pjsip/transport.generated.conf",
);
const defaultExtensionsIndexFile = path.join(
  workspaceRoot,
  "infra/asterisk/generated/extensions/stack-pbx.generated.conf",
);

type ProvisionDeviceInput = {
  deviceId: string;
  deviceName: string;
  extension: string;
  groupId: string;
  mqttTopic: string;
  sipPassword: string;
  sipUser: string;
};

type ProvisionUserInput = {
  userId: string;
  userName: string;
  extension: string;
  sipPassword: string;
  sipUser: string;
};

const ASTERISK_AMI_COMMAND_TIMEOUT_MS = 5000;
const DEVICE_REGISTRATION_WAIT_TIMEOUT_MS = 20000;
const DEVICE_REGISTRATION_POLL_INTERVAL_MS = 2000;

function getPjsipDevicesDir() {
  return env.ASTERISK_GENERATED_PJSIP_DIR ?? defaultPjsipDevicesDir;
}

function getExtensionsGroupsDir() {
  return env.ASTERISK_GENERATED_EXTENSIONS_DIR ?? defaultExtensionsGroupsDir;
}

function getPjsipIndexFile() {
  return path.join(path.dirname(getPjsipDevicesDir()), path.basename(defaultPjsipIndexFile));
}

function getPjsipTransportFile() {
  return path.join(path.dirname(getPjsipDevicesDir()), path.basename(defaultPjsipTransportFile));
}

function getExtensionsIndexFile() {
  return path.join(
    path.dirname(getExtensionsGroupsDir()),
    path.basename(defaultExtensionsIndexFile),
  );
}

function getGroupContextName(groupId: string) {
  return `${env.ASTERISK_DIALPLAN_CONTEXT_PREFIX}-${sanitizeSipToken(groupId)}`;
}

function getUsersContextName() {
  return `${env.ASTERISK_DIALPLAN_CONTEXT_PREFIX}-users`;
}

function buildEndpointNames(sipUser: string) {
  const baseName = sanitizeSipToken(sipUser);

  return {
    endpoint: baseName,
    auth: `${baseName}-auth`,
    aor: baseName,
  };
}

export function buildPjsipEndpointName(input: { sipUser: string }) {
  return buildEndpointNames(input.sipUser).endpoint;
}

export async function userPjsipConfigNeedsReprovision(userId: string) {
  const pjsipFilePath = path.join(getPjsipDevicesDir(), `${userId}.conf`);

  try {
    const contents = await readFile(pjsipFilePath, "utf8");

    return (
      !contents.includes("transport=transport-ws") ||
      !contents.includes("webrtc=yes") ||
      !contents.includes("allow=ulaw,alaw")
    );
  } catch {
    return true;
  }
}

function buildDevicePjsipConfig(input: ProvisionDeviceInput) {
  const names = buildEndpointNames(input.sipUser);
  const contextName = getGroupContextName(input.groupId);

  return `; Auto-generated by stack-pbx. Manual edits will be overwritten.\n[${names.endpoint}]\ntype=endpoint\ntransport=${env.ASTERISK_PJSIP_TRANSPORT}\ncontext=${contextName}\ndisallow=all\nallow=ulaw,alaw\naors=${names.aor}\nauth=${names.auth}\nidentify_by=auth_username,username\ndirect_media=no\nrtp_symmetric=yes\nforce_rport=yes\nrewrite_contact=yes\ncallerid=${JSON.stringify(input.deviceName)} <${input.extension}>\nset_var=DEVICE_ID=${input.deviceId}\nset_var=DEVICE_EXTENSION=${input.extension}\nset_var=DEVICE_MQTT_TOPIC=${input.mqttTopic}\n\n[${names.auth}]\ntype=auth\nauth_type=userpass\nusername=${input.sipUser}\npassword=${input.sipPassword}\n\n[${names.aor}]\ntype=aor\nmax_contacts=1\nremove_existing=yes\nqualify_frequency=30\n`;
}

function buildTransportConfig() {
  const externalHost = env.ASTERISK_DEVICE_HOST?.trim();
  const mediaAddressLines = externalHost
    ? [`external_media_address=${externalHost}`, `external_signaling_address=${externalHost}`]
    : [];

  return [
    "; Auto-generated by stack-pbx. Manual edits will be overwritten.",
    "[transport-udp]",
    "type=transport",
    "protocol=udp",
    "bind=0.0.0.0:5060",
    ...mediaAddressLines,
    "",
    "[transport-ws]",
    "type=transport",
    "protocol=ws",
    "bind=0.0.0.0",
    ...mediaAddressLines,
    "",
  ].join("\n");
}

function buildUserPjsipConfig(input: ProvisionUserInput) {
  const names = buildEndpointNames(input.sipUser);
  const contextName = getUsersContextName();

  return `; Auto-generated by stack-pbx. Manual edits will be overwritten.\n[${names.endpoint}]\ntype=endpoint\ntransport=transport-ws\ncontext=${contextName}\ndisallow=all\nallow=ulaw,alaw\naors=${names.aor}\nauth=${names.auth}\nidentify_by=auth_username,username\ndirect_media=no\nrtp_symmetric=yes\nforce_rport=yes\nrewrite_contact=yes\ncallerid=${JSON.stringify(input.userName)} <${input.extension}>\nwebrtc=yes\ndtls_auto_generate_cert=yes\nmedia_encryption=dtls\nice_support=yes\nmedia_use_received_transport=yes\nrtcp_mux=yes\nset_var=USER_ID=${input.userId}\nset_var=USER_EXTENSION=${input.extension}\n\n[${names.auth}]\ntype=auth\nauth_type=userpass\nusername=${input.sipUser}\npassword=${input.sipPassword}\n\n[${names.aor}]\ntype=aor\nmax_contacts=1\nremove_existing=yes\nqualify_frequency=30\n`;
}

function buildGroupDialplan(input: {
  groupId: string;
  groupExtension?: string | null;
  devices: Array<{ extension: string; sipUser: string }>;
}) {
  const contextName = getGroupContextName(input.groupId);
  const ringTargets = input.devices
    .map((device) => `PJSIP/${buildPjsipEndpointName({ sipUser: device.sipUser })}`)
    .join("&");
  const deviceRoutes = input.devices
    .map(
      (device) =>
        `exten => ${device.extension},1,NoOp(Stack PBX device ${device.extension})\n same => n,Dial(PJSIP/${buildPjsipEndpointName({ sipUser: device.sipUser })},30)\n same => n,Hangup()`,
    )
    .join("\n");
  const groupRoute = input.groupExtension
    ? ringTargets
      ? `exten => ${input.groupExtension},1,NoOp(Stack PBX group ${input.groupId})\n same => n,Page(${ringTargets},d)\n same => n,Hangup()`
      : `exten => ${input.groupExtension},1,Playback(vm-nobodyavail)\n same => n,Hangup()`
    : "";
  const directoryFallback = [
    "exten => _X!,1,NoOp(Stack PBX outbound from device ${CALLERID(num)} to ${EXTEN})",
    ` same => n,Goto(${env.ASTERISK_DIALPLAN_CONTEXT_PREFIX}-directory,\${EXTEN},1)`,
  ].join("\n");

  return `; Auto-generated by stack-pbx. Manual edits will be overwritten.\n[${contextName}]\n${[groupRoute, deviceRoutes, directoryFallback].filter(Boolean).join("\n")}\n`;
}

function buildUsersDialplan() {
  return [
    "; Auto-generated by stack-pbx. Manual edits will be overwritten.",
    `[${getUsersContextName()}]`,
    "exten => _X!,1,NoOp(Stack PBX outbound from user ${CALLERID(num)} to ${EXTEN})",
    ` same => n,Goto(${env.ASTERISK_DIALPLAN_CONTEXT_PREFIX}-directory,\${EXTEN},1)`,
    "",
  ].join("\n");
}

function buildDirectoryDialplan(input: {
  users: Array<{ extension: string; sipUser: string }>;
  groups: Array<{
    id: string;
    extension: string | null;
    devices: Array<{ extension: string; sipUser: string }>;
  }>;
}) {
  const lines = [
    "; Auto-generated by stack-pbx. Manual edits will be overwritten.",
    `[${env.ASTERISK_DIALPLAN_CONTEXT_PREFIX}-directory]`,
  ];

  for (const user of input.users) {
    lines.push(`exten => ${user.extension},1,NoOp(Stack PBX user ${user.extension})`);
    lines.push(` same => n,Dial(PJSIP/${buildPjsipEndpointName({ sipUser: user.sipUser })},30)`);
    lines.push(" same => n,Hangup()");
  }

  for (const group of input.groups) {
    for (const device of group.devices) {
      lines.push(`exten => ${device.extension},1,NoOp(Stack PBX device ${device.extension})`);
      lines.push(
        ` same => n,Dial(PJSIP/${buildPjsipEndpointName({ sipUser: device.sipUser })},30)`,
      );
      lines.push(" same => n,Hangup()");
    }

    if (group.extension) {
      lines.push(`exten => ${group.extension},1,NoOp(Stack PBX group ${group.id})`);
      lines.push(` same => n,Goto(${getGroupContextName(group.id)},${group.extension},1)`);
      lines.push(" same => n,Hangup()");
    }
  }

  lines.push("exten => _X!,1,Playback(invalid)");
  lines.push(" same => n,Hangup()");
  lines.push("");
  return lines.join("\n");
}

async function writeIncludeIndex(options: {
  childDir: string;
  indexFile: string;
  includePrefix?: string;
}) {
  await mkdir(options.childDir, { recursive: true });

  const childEntries = (await readdir(options.childDir))
    .filter((fileName) => fileName.endsWith(".conf"))
    .sort((left, right) => left.localeCompare(right));

  const includePrefix =
    options.includePrefix ??
    [
      "generated",
      path.basename(path.dirname(options.indexFile)),
      path.basename(options.childDir),
    ].join("/");

  const contents = [
    "; Auto-generated by stack-pbx. Manual edits will be overwritten.",
    ...childEntries.map((fileName) => `#include "${includePrefix}/${fileName}"`),
    "",
  ].join("\n");

  await mkdir(path.dirname(options.indexFile), { recursive: true });
  await writeFile(options.indexFile, contents, "utf8");
}

async function removeConflictingPjsipFiles(options: {
  currentFilePath: string;
  pjsipDevicesDir: string;
  sipUser: string;
}) {
  const endpointName = buildEndpointNames(options.sipUser).endpoint;
  const childEntries = (await readdir(options.pjsipDevicesDir))
    .filter((fileName) => fileName.endsWith(".conf"))
    .sort((left, right) => left.localeCompare(right));

  for (const fileName of childEntries) {
    const filePath = path.join(options.pjsipDevicesDir, fileName);

    if (filePath === options.currentFilePath) {
      continue;
    }

    const contents = await readFile(filePath, "utf8");

    if (contents.includes(`[${endpointName}]`)) {
      await rm(filePath, { force: true });
    }
  }
}

function ensureAsteriskProvisioningIsConfigured() {
  if (!env.ASTERISK_AUTO_PROVISION) {
    return;
  }

  if (!env.ASTERISK_AMI_HOST || !env.ASTERISK_AMI_USERNAME || !env.ASTERISK_AMI_PASSWORD) {
    throw new AppError("ASTERISK_NOT_CONFIGURED");
  }
}

function isAmiPositiveResponse(packet: string) {
  return packet.includes("Response: Success") || packet.includes("Response: Follows");
}

async function runAsteriskCommandOverAmi(options: {
  actionId: string;
  command: string;
  errorCode: "ASTERISK_RELOAD_FAILED" | "DEVICE_CREATION_FAILED";
  timeoutMessage: string;
}) {
  ensureAsteriskProvisioningIsConfigured();

  return await new Promise<string>((resolve, reject) => {
    const socket = net.createConnection({
      host: env.ASTERISK_AMI_HOST,
      port: env.ASTERISK_AMI_PORT,
    });
    const loginActionId = `login-${Date.now()}-${options.actionId}`;
    let buffer = "";
    let settled = false;

    const finish = (result?: string, error?: AppError) => {
      if (settled) {
        return;
      }

      settled = true;
      clearTimeout(timeout);
      socket.end();

      if (error) {
        reject(error);
        return;
      }

      resolve(result ?? "");
    };

    const timeout = setTimeout(() => {
      finish(undefined, new AppError(options.errorCode, { message: options.timeoutMessage }));
    }, ASTERISK_AMI_COMMAND_TIMEOUT_MS);

    socket.on("connect", () => {
      socket.write(
        `Action: Login\r\nUsername: ${env.ASTERISK_AMI_USERNAME}\r\nSecret: ${env.ASTERISK_AMI_PASSWORD}\r\nActionID: ${loginActionId}\r\n\r\n`,
      );
    });

    socket.on("data", (chunk) => {
      buffer += chunk.toString("utf8");

      while (buffer.includes("\r\n\r\n")) {
        const separatorIndex = buffer.indexOf("\r\n\r\n");
        const packet = buffer.slice(0, separatorIndex);
        buffer = buffer.slice(separatorIndex + 4);

        if (packet.includes(`ActionID: ${loginActionId}`) && isAmiPositiveResponse(packet)) {
          socket.write(
            `Action: Command\r\nCommand: ${options.command}\r\nActionID: ${options.actionId}\r\n\r\n`,
          );
          continue;
        }

        if (packet.includes(`ActionID: ${options.actionId}`)) {
          if (isAmiPositiveResponse(packet)) {
            socket.write("Action: Logoff\r\n\r\n");
            finish(packet);
            return;
          }

          finish(
            undefined,
            new AppError(options.errorCode, {
              message: `Asterisk AMI command failed for "${options.command}": ${packet}`,
            }),
          );
          return;
        }
      }
    });

    socket.on("error", (error) => {
      finish(
        undefined,
        new AppError(options.errorCode, {
          message: `Asterisk AMI connection failed for "${options.command}": ${error.message}`,
        }),
      );
    });
  });
}

function sleep(ms: number) {
  return new Promise<void>((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function reloadAsteriskOverAmi() {
  if (!env.ASTERISK_AUTO_PROVISION) {
    return;
  }

  await runAsteriskCommandOverAmi({
    actionId: `reload-dialplan-${Date.now()}`,
    command: "dialplan reload",
    errorCode: "ASTERISK_RELOAD_FAILED",
    timeoutMessage: "Timed out while reloading the Asterisk dialplan through AMI",
  });

  await runAsteriskCommandOverAmi({
    actionId: `reload-pjsip-${Date.now()}`,
    command: "pjsip reload",
    errorCode: "ASTERISK_RELOAD_FAILED",
    timeoutMessage: "Timed out while reloading Asterisk PJSIP through AMI",
  });
}

async function writeSharedDialplanFiles() {
  const users = await db
    .select({
      extension: userTable.extension,
      sipUser: userTable.sipUser,
    })
    .from(userTable);

  const groups = await db.query.deviceGroup.findMany({
    columns: {
      id: true,
      extension: true,
    },
  });

  const deviceRows = await db
    .select({
      groupId: deviceTable.groupId,
      extension: deviceTable.extension,
      sipUser: deviceTable.sipUser,
    })
    .from(deviceTable);

  const devicesByGroup = new Map<string, Array<{ extension: string; sipUser: string }>>();

  for (const device of deviceRows) {
    const current = devicesByGroup.get(device.groupId) ?? [];
    current.push({ extension: device.extension, sipUser: device.sipUser });
    devicesByGroup.set(device.groupId, current);
  }

  const extensionsGroupsDir = getExtensionsGroupsDir();
  await mkdir(extensionsGroupsDir, { recursive: true });
  await writeFile(path.join(extensionsGroupsDir, "users.conf"), buildUsersDialplan(), "utf8");
  await writeFile(
    path.join(extensionsGroupsDir, "directory.conf"),
    buildDirectoryDialplan({
      users: users.filter((user): user is { extension: string; sipUser: string } =>
        Boolean(user.extension && user.sipUser),
      ),
      groups: groups.map((group) => ({
        id: group.id,
        extension: group.extension,
        devices: devicesByGroup.get(group.id) ?? [],
      })),
    }),
    "utf8",
  );
}

async function writePjsipTransportConfig() {
  const transportFile = getPjsipTransportFile();
  await mkdir(path.dirname(transportFile), { recursive: true });
  await writeFile(transportFile, buildTransportConfig(), "utf8");
}

export async function waitForDeviceRegistrationInAsterisk(input: {
  sipUser: string;
  timeoutMs?: number;
}) {
  if (!env.ASTERISK_AUTO_PROVISION) {
    return;
  }

  const names = buildEndpointNames(input.sipUser);
  const deadline = Date.now() + (input.timeoutMs ?? DEVICE_REGISTRATION_WAIT_TIMEOUT_MS);

  while (Date.now() < deadline) {
    const commandOutput = await runAsteriskCommandOverAmi({
      actionId: `contacts-${Date.now()}`,
      command: "pjsip show contacts",
      errorCode: "DEVICE_CREATION_FAILED",
      timeoutMessage: "Timed out while checking device registration status in Asterisk",
    });

    if (commandOutput.includes(`${names.aor}/sip:`)) {
      return;
    }

    await sleep(DEVICE_REGISTRATION_POLL_INTERVAL_MS);
  }

  throw new AppError("DEVICE_CREATION_FAILED");
}

export async function provisionDeviceInAsterisk(input: ProvisionDeviceInput) {
  if (!env.ASTERISK_AUTO_PROVISION) {
    return;
  }

  ensureAsteriskProvisioningIsConfigured();

  const pjsipDevicesDir = getPjsipDevicesDir();
  const extensionsGroupsDir = getExtensionsGroupsDir();
  const pjsipFilePath = path.join(pjsipDevicesDir, `${input.deviceId}.conf`);

  const group = await db.query.deviceGroup.findFirst({
    where: eq(deviceGroupTable.id, input.groupId),
    columns: { extension: true },
  });

  const devices = await db
    .select({
      extension: deviceTable.extension,
      sipUser: deviceTable.sipUser,
    })
    .from(deviceTable)
    .where(eq(deviceTable.groupId, input.groupId));

  await mkdir(pjsipDevicesDir, { recursive: true });
  await mkdir(extensionsGroupsDir, { recursive: true });
  await writePjsipTransportConfig();

  await removeConflictingPjsipFiles({
    currentFilePath: pjsipFilePath,
    pjsipDevicesDir,
    sipUser: input.sipUser,
  });

  await writeFile(pjsipFilePath, buildDevicePjsipConfig(input), "utf8");
  await writeFile(
    path.join(extensionsGroupsDir, `${sanitizeSipToken(input.groupId)}.conf`),
    buildGroupDialplan({
      groupId: input.groupId,
      groupExtension: group?.extension,
      devices,
    }),
    "utf8",
  );
  await writeSharedDialplanFiles();
  await writeIncludeIndex({
    childDir: pjsipDevicesDir,
    indexFile: getPjsipIndexFile(),
    includePrefix: "generated/pjsip/devices",
  });
  await writeIncludeIndex({
    childDir: extensionsGroupsDir,
    indexFile: getExtensionsIndexFile(),
  });
  await reloadAsteriskOverAmi();
}

export async function provisionUserInAsterisk(input: ProvisionUserInput) {
  if (!env.ASTERISK_AUTO_PROVISION) {
    return;
  }

  ensureAsteriskProvisioningIsConfigured();

  const pjsipDevicesDir = getPjsipDevicesDir();
  const pjsipFilePath = path.join(pjsipDevicesDir, `${input.userId}.conf`);

  await mkdir(pjsipDevicesDir, { recursive: true });
  await writePjsipTransportConfig();
  await removeConflictingPjsipFiles({
    currentFilePath: pjsipFilePath,
    pjsipDevicesDir,
    sipUser: input.sipUser,
  });
  await writeFile(pjsipFilePath, buildUserPjsipConfig(input), "utf8");
  await writeSharedDialplanFiles();
  await writeIncludeIndex({
    childDir: pjsipDevicesDir,
    indexFile: getPjsipIndexFile(),
    includePrefix: "generated/pjsip/devices",
  });
  await writeIncludeIndex({
    childDir: getExtensionsGroupsDir(),
    indexFile: getExtensionsIndexFile(),
  });
  await reloadAsteriskOverAmi();
}

export async function removeDeviceFromAsterisk(input: { deviceId: string }) {
  if (!env.ASTERISK_AUTO_PROVISION) {
    return;
  }

  const pjsipDevicesDir = getPjsipDevicesDir();
  await writePjsipTransportConfig();
  await rm(path.join(pjsipDevicesDir, `${input.deviceId}.conf`), { force: true });
  await writeIncludeIndex({
    childDir: pjsipDevicesDir,
    indexFile: getPjsipIndexFile(),
    includePrefix: "generated/pjsip/devices",
  });
  await writeIncludeIndex({
    childDir: getExtensionsGroupsDir(),
    indexFile: getExtensionsIndexFile(),
  });
  await reloadAsteriskOverAmi();
}

export async function syncGroupDialplanInAsterisk(groupId: string) {
  if (!env.ASTERISK_AUTO_PROVISION) {
    return;
  }

  await writePjsipTransportConfig();

  const group = await db.query.deviceGroup.findFirst({
    where: eq(deviceGroupTable.id, groupId),
    columns: {
      id: true,
      extension: true,
    },
  });

  if (!group) {
    return;
  }

  const devices = await db
    .select({
      extension: deviceTable.extension,
      sipUser: deviceTable.sipUser,
    })
    .from(deviceTable)
    .where(eq(deviceTable.groupId, groupId));

  await mkdir(getExtensionsGroupsDir(), { recursive: true });
  await writeFile(
    path.join(getExtensionsGroupsDir(), `${sanitizeSipToken(group.id)}.conf`),
    buildGroupDialplan({
      groupId: group.id,
      groupExtension: group.extension,
      devices,
    }),
    "utf8",
  );
  await writeSharedDialplanFiles();
  await writeIncludeIndex({
    childDir: getExtensionsGroupsDir(),
    indexFile: getExtensionsIndexFile(),
  });
  await reloadAsteriskOverAmi();
}
