[global]
type=global
user_agent=stack-pbx
endpoint_identifier_order=auth_username,username,ip,anonymous

#include "generated/pjsip/transport.generated.conf"
#include "generated/pjsip/stack-pbx.generated.conf"
